title: Alexandre's blog
email: erdnaxe@crans.org
description: >- 
  Random stuff randomly written.
baseurl: ""
url: "https://alexandre.iooss.fr"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme customisation
github_username: erdnaxe

minima:
  date_format: "%b %Y"
  skin: solarized

rss: RSS feed

disqus:
    shortname: erdnaxe-github-io

google_analytics: UA-73415056-1

header_pages:
 - categories/custom_firmware.html
 - categories/microcontroller.html
 - categories/3d_printer.html
 - categories/miscellaneous.html
 - about.md

permalink: /:title/

