baseURL: https://blog.nanax.fr/
title: erdnaxe's blog
paginate: 5
theme: custom

enableRobotsTXT: true
enableEmoji: true

markup:
  highlight:
    lineNos: true

menu:
  main:
  - name: Intranet
    url: https://intranet.crans.org/login/
    weight: 50

params:
  keywords: [blog, erdnaxe, hardware, software, system, administration]
  author: Alexandre Iooss
  homeInfoParams:
    Title: "Welcome to my blog 🦋"
    Content: |
      ## Highlighted projects
      - [grimorio](https://grimorio.org/) &ndash; Index services options from various GNU/Linux distributions
      - [bmpc](https://github.com/erdnaxe/bmpc) &ndash; Minimalist Music Player Deamon client in browser
      - [web2pdf](https://github.com/erdnaxe/web2pdf/) &ndash; Print any web page as PDF document, even JavaScript generated ones
      - [pass-group](https://github.com/erdnaxe/pass-group/) &ndash; Group password manager extension for the standard unix password manager
      - [galene-stream](https://github.com/erdnaxe/galene-stream/) &ndash; Experiment to stream live feeds to Galène videoconference server
      - [kraby](https://kraby.readthedocs.io/en/latest/) &ndash; Open source 3d-printable hexapod robot with OpenAI Gym environment
      - [screenger](https://github.com/erdnaxe/screenger/) &ndash; Experiment to abuse coil whine to make some screens play music

      On my free time I also contribute to other open source projects and volunteer at [Crans](https://www.crans.org/fr/), [Aurore](https://auro.re/) and [RezoSup](https://www.rezosup.org/map.php) organizations.
  socialIcons:
    - name: github
      url: "https://github.com/erdnaxe"
    - name: email
      url: "mailto:a+blog@crans.org"
    - name: rss
      url: "/index.xml"
  editPost:
    URL: "https://github.com/erdnaxe/blog.nanax.fr/blob/master/content"
    appendFilePath: true

menu:
  main:
    - identifier: hardware
      name: hardware
      url: /categories/hardware
      weight: 10
    - identifier: software
      name: software
      url: /categories/software
      weight: 11
    - identifier: system-administration
      name: system administration
      url: /categories/system-administration
      weight: 12
    - identifier: about
      name: about
      url: /about/
      weight: 20
