baseURL: https://blog.nanax.fr/
title: erdnaxe's blog
paginate: 10

enableRobotsTXT: true
enableEmoji: true

markup:
  highlight:
    lineNos: true

params:
  keywords: [blog, erdnaxe, hardware, software, system, administration]
  description: Blog posts about hardware development and system administration.
  author: Alexandre Iooss
  homeInfoParams:
    Content: |
      ## Highlighted projects
      - [bmpc](https://github.com/erdnaxe/bmpc) &ndash; Minimalist Music Player Deamon client in browser
      - [pass-group](https://github.com/erdnaxe/pass-group/) &ndash; Group password manager extension for the standard unix password manager
      - [galene-stream](https://github.com/erdnaxe/galene-stream/) &ndash; Experiment to stream live feeds to Galène videoconference server
      - [kraby](https://kraby.readthedocs.io/en/latest/) &ndash; Open source 3d-printable hexapod robot with OpenAI Gym environment
      - [screenger](https://github.com/erdnaxe/screenger/) &ndash; Experiment to abuse coil whine to make some screens play music
      - [sandboxdb.org](https://sandboxdb.org/) &ndash; Index sandboxing options from various GNU/Linux distributions
  socialIcons:
    - name: github
      url: "https://github.com/erdnaxe"
    - name: email
      url: "mailto:a+blog@crans.org"
    - name: rss
      url: "/index.xml"
  editPost:
    URL: "https://github.com/erdnaxe/blog.nanax.fr/blob/master/content"
    appendFilePath: true

menu:
  main:
    - identifier: hardware
      name: hardware
      url: /categories/hardware
      weight: 10
    - identifier: system-administration
      name: system administration
      url: /categories/system-administration
      weight: 12
    - identifier: about
      name: about
      url: /about/
      weight: 20
